# Generated by Django 5.1.7 on 2025-07-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0009_alter_jobs_location_alter_jobs_qualification'),
        ('jobapp', '0006_tags_jobseeker_seeker_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_tags',
            field=models.ManyToManyField(blank=True, to='jobapp.tags'),
        ),
    ]
