# Generated by Django 5.1.7 on 2025-07-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_alter_employer_regdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='seeker_tags',
            field=models.ManyToManyField(blank=True, to='jobapp.tags'),
        ),
    ]
